# The directory from which notification templates are read.
templates: 
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: 'YOUR WEBHOOK URL'

