groups:
  - name: Container Monitoring
    rules:
      # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
      - alert: ContainerKilled
        expr: time() - container_last_seen > 20
        for: 0m
        labels:
          severity: warning
        annotations:
          title: Container killed ({{ $labels.name }})
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"