global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-host-alpha'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']